runtime: python39
service: website-service
instance_class: F2

handlers:
- url: /(.*\.(html|css|js))$
  static_files: \1
  upload: (.*\.(html|css|js))$
- url: /.*
  static_files: index.html
  upload: Landing.html